### PR TITLE
When getting scripts, ensure there's an active context

### PR DESCRIPTION
**Pull request by akrantz**
JsDiagGetScripts() will return JsNoCurrentContext if there's not an active context. Ensure there is an active context so it can return the scripts.

### CODE REVIEW

**Comment by kfarnung** [comment]
In the process of writing a test for the fix I ran into more issues.  I think this should be a complete fix.  @akrantz can you try it out?

**Comment by kfarnung** [comment]
@digitalinfinity Does this look reasonable to you?

**Comment by akrantz** [comment]
@kfarnung The updated code works in terms of being able to return scripts when GetScripts() is called. However, the script is loaded as "Unknown script code" and therefore debugging doesn't work. The source is built by webpack into "index.win32.bundle.js" and has associate source map "index.win32.bundle.js.map". 

The VS Code debugger trace shows:
```
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"1","url":"Unknown script code","startLine":0,"startColumn":0,"endLine":15,"endColumn":0,"executionContextId":0,"hash":"","isLiveEdit":false,"sourceMapURL":"index.win32.bundle.map","hasSourceURL":false}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"3","url":"Unknown script code","startLine":0,"startColumn":0,"endLine":2,"endColumn":0,"executionContextId":0,"hash":"","isLiveEdit":false,"sourceMapURL":"index.win32.bundle.js.map","hasSourceURL":false}}
```

I'm unclear why the url here is "Unknown script code".

The script is loaded via a call to JsRun() for two bundles. The first is "excel-udf-host.win32.bundle" which is for the custom function runtime code. The second is "index.win32.bundle" which is the script built for my Excel add-in.

**Comment by akrantz** [comment]
I didn't have breakpoints set but hitting pause in VSCode will generate a break event followed by getting source. I have tracepoints in VS on protocol message request and response:
```
{"type":"request","payload":{"id":25,"method":"Debugger.getScriptSource","params":{"scriptId":"1"}}},
{"type":"response","payload":{"id":25,"result":{"scriptSource":"!function(e){var t={};function n(r){if....
```

**Comment by akrantz** [comment]
@digitalinfinity  The comment above shows the service handler providing the script source but it's not appearing in VS Code or Chrome. Since Kyle is on vacation, it would help if someone else can assist with understanding what's going on here. I'm continuing to drill into this and find out.

**Comment by akrantz** [comment]
@kfarnung @digitalinfinity I made progress yesterday in getting the scripts to show. There are two JavaScript files loaded use JsCreateExternalArrayBuffer/JsRun(). The Office runtime code was specifying JS_NO_SOURCE_CONTEXT (-1) for the script context parameter. I updated the code to pass 0/1 to the calls. The scripts now show up in VS Code. 

However, breakpoints are not working. I'll be investigating this more today.

One other thing I noticed is that the calculation of the hash is not implemented. As two scripts could share the same filename, I am wondering if we should have the hash calculated so it can differentiate between two different files with the same name.

I also have made changes to the sample exe to add a --buffer argument which allows it to load the script using JsCreateExternalArrayBuffer/JsRun instead of RunScript. 

I would like to have the sample exe support multiple script files, but hadn't come up with the best way to do this. Right now, the first arg is the script and the rest of the args are specified for that script. I am considering adding a --script parameter which can be used to add additional scripts. This would allow the additional script(s) to be loaded and run first (without args), and then the main script is run with args as is done now. Another approach might be to use "--" to separate scripts and each group between "--" would be a script with its args, so each group can be have args specified and run.

**Comment by akrantz** [comment]
@kfarnung @digitalinfinity Having found and fixed the problem in my code causing the deadlock when processing the command queue, this looks good. I made a separate PR for the sample exe changes.

**Pull request merged**
