### PR TITLE
Fix visibility of GetProtocolHandler()

### PR DESCRIPTION
**Pull request by akrantz**
Making this public allows it to build and the tests pass.

### CODE REVIEW

**Comment by akrantz** [comment]
Actually, the callbackState has the JsDebugProtocolHandler* returned from GetProtocolHandler(), so it should just cast to that instead of JsrtDebugTestFixture*.

**Comment by kfarnung** [comment]
I'm confused, isn't this making it less visible?

**Comment by akrantz** [comment]
I'm confused too because i thought it was removing protected. Does master build and run OK for you?

**Comment by kfarnung** [comment]
Yup, works fine here:

```
===============================================================================
All tests passed (78 assertions in 5 test cases)


E:\GitHub\ChakraCore-Debugger\build\bin\x64\Debug\ChakraCore.Debugger.UnitTests.exe (process 31560) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by akrantz** [comment]
OK, I went back to master and it also works for me. Sorry about the confusion.

**Pull request closed without merging**
