### PR TITLE
Update ChakraCore to v1.11.15

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by akrantz** [comment]
@JunielKatarn I encountered errors doing a batch build of the solution for all flavors and platforms.

I think there may be some issue with x86 versus ARM here.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.Protocol	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.Protocol\Common.obj	1	
Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.ProtocolHandler	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.ProtocolHandler\ConsoleHandler.obj	1	
Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.Service	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.Service\ChakraDebugService.obj	1	
Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger.Sample	C:\dev\git\ChakraCore-Debugger\bin\Debugger.Sample\LINK	1	
Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger.UnitTests	C:\dev\git\ChakraCore-Debugger\test\Debugger.UnitTests\LINK	1	
Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger	C:\dev\git\ChakraCore-Debugger\bin\Debugger\LINK	1	

```

**Comment by JunielKatarn** [comment]
> @JunielKatarn I encountered errors doing a batch build of the solution for all flavors and platforms.
> 
> I think there may be some issue with x86 versus ARM here.
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.Protocol	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.Protocol\Common.obj	1	
> Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.ProtocolHandler	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.ProtocolHandler\ConsoleHandler.obj	1	
> Error	LNK1112	module machine type 'x86' conflicts with target machine type 'ARM'	ChakraCore.Debugger.Service	C:\dev\git\ChakraCore-Debugger\build\obj\ARM\Debug\ChakraCore.Debugger.Service\ChakraDebugService.obj	1	
> Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger.Sample	C:\dev\git\ChakraCore-Debugger\bin\Debugger.Sample\LINK	1	
> Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger.UnitTests	C:\dev\git\ChakraCore-Debugger\test\Debugger.UnitTests\LINK	1	
> Error	LNK1104	cannot open file 'C:\dev\git\ChakraCore-Debugger\build\bin\ARM\Debug\ChakraCore.Debugger.Protocol.lib'	ChakraCore.Debugger	C:\dev\git\ChakraCore-Debugger\bin\Debugger\LINK	1	
> ```

I have not encountered this before.
What command did you issue?

**Comment by akrantz** [comment]
Build -> Batch Build... , then Select All and Rebuild.

image

**Comment by akrantz** [comment]
I used VS 2019.

**Pull request closed without merging**
